name: cd
permissions:
  contents: read
on:
  push:
    branches:
      - main
jobs:
  vite:
    permissions:
      pages: write
      id-token: write
    uses: umts/.github/.github/workflows/deploy-vite-app.yml@main
