name: push
permissions:
  contents: read
on:
  push:
    branches:
      - main
jobs:
  integrate:
    uses: umts/.github/.github/workflows/integrate-vite.yml@b0d150353b4fc582a29ef2f39e64cd7f1ef02855
  deploy:
    needs: integrate
    permissions:
      pages: write
      id-token: write
    uses: umts/.github/.github/workflows/deploy-pages-vite.yml@main
